#!/bin/sh -
cat <<'EOF'
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.0 present.
90 structures occupying 4575 bytes.
Table at 0x000EB000.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Amazon EC2
	Version: 1.0
	Release Date: 10/16/2017
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 8192 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		BIOS ROM is socketed
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 5.11

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Amazon EC2
	Product Name: i3.metal
	Version: 00001
	Serial Number: ec2240c6-8e37-edcf-72ac-7951361680f2
	UUID: EC2240C6-8E37-EDCF-72AC-7951361680F2
	Wake-up Type: Power Switch
	SKU Number:                     
	Family: 110-000523-002

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: Amazon EC2
	Product Name: Not Specified
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: i-035891f969d0ff36b
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: empty
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0

Handle 0x0003, DMI type 3, 25 bytes
Chassis Information
	Manufacturer: Amazon EC2
	Type: Rack Mount Chassis
	Lock: Not Present
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: Amazon EC2
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: None
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: 1
	Contained Elements: 1
		<OUT OF SPEC> (0)
	SKU Number: To be filled by O.E.M

Handle 0x0004, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J17
	Internal Connector Type: None
	External Reference Designator: MEZZ_0
	External Connector Type: RJ-45
	Port Type: Network Port

Handle 0x0005, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J99
	Internal Connector Type: None
	External Reference Designator: MEZZ_1
	External Connector Type: RJ-45
	Port Type: Network Port

Handle 0x0006, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J43
	Internal Connector Type: None
	External Reference Designator: External USB0 Port 0
	External Connector Type: Access Bus (USB)
	Port Type: USB

Handle 0x0007, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J43
	Internal Connector Type: None
	External Reference Designator: External USB0 Port 1
	External Connector Type: Access Bus (USB)
	Port Type: USB

Handle 0x0008, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: VGA1
	Internal Connector Type: None
	External Reference Designator: VGA
	External Connector Type: DB-15 female
	Port Type: Video Port

Handle 0x0009, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J124
	Internal Connector Type: None
	External Reference Designator: COM Port
	External Connector Type: DB-9 male
	Port Type: Serial Port 16550A Compatible

Handle 0x000A, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J158
	Internal Connector Type: None
	External Reference Designator: Mgt_LAN
	External Connector Type: RJ-45
	Port Type: Network Port

Handle 0x000B, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J98 - PCIE RISER_0
	Internal Connector Type: Other
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: Other

Handle 0x000C, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J102 - PCIE RISER_1
	Internal Connector Type: Other
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: Other

Handle 0x000D, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J110 - SATA_0
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SATA

Handle 0x000E, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J111 - SATA_1
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SATA

Handle 0x000F, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J100 - PCIeSSD_0
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0010, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J101 - PCIeSSD_1
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0011, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J104 - PCIeSSD_2
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0012, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J105 - PCIeSSD_3
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0013, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J107 - PCIeSSD_4
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0014, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J106 - PCIeSSD_5
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0015, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J108 - PCIeSSD_6
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0016, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J109 - PCIeSSD_7
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SAS

Handle 0x0017, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J96 - TPM
	Internal Connector Type: Other
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: Other

Handle 0x0018, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J135 - Internal USB1
	Internal Connector Type: Access Bus (USB)
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: USB

Handle 0x0019, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J136 - Internal USB2
	Internal Connector Type: Access Bus (USB)
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: USB

Handle 0x001A, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J40 - SATA CONN(0-3)
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SATA

Handle 0x001B, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J41 - SATA CONN(4-7)
	Internal Connector Type: SAS/SATA Plug Receptacle
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: SATA

Handle 0x001C, DMI type 8, 9 bytes
Port Connector Information
	Internal Reference Designator: J56 - Front USB Port 0 & Port1
	Internal Connector Type: Access Bus (USB)
	External Reference Designator: Not Specified
	External Connector Type: None
	Port Type: USB

Handle 0x001D, DMI type 9, 17 bytes
System Slot Information
	Designation: RISER0_SLOT0
	Type: x16 PCI Express 3 x16
	Current Usage: In Use
	Length: Long
	ID: 1
	Characteristics:
		3.3 V is provided
		Opening is shared
		PME signal is supported
	Bus Address: 0000:02:03.0

Handle 0x001E, DMI type 9, 17 bytes
System Slot Information
	Designation: RISER1_SLOT0
	Type: x16 PCI Express 3 x16
	Current Usage: Available
	Length: Long
	ID: 2
	Characteristics:
		3.3 V is provided
		Opening is shared
		PME signal is supported
	Bus Address: 0000:ff:01.0

Handle 0x001F, DMI type 10, 6 bytes
On Board Device Information
	Type: Video
	Status: Enabled
	Description:    AST2400

Handle 0x0020, DMI type 11, 5 bytes
OEM Strings
	String 1: empty
	String 2: empty
	String 3: empty
	String 4: empty
	String 5: empty

Handle 0x0021, DMI type 12, 5 bytes
System Configuration Options
	Option 1: Default string

Handle 0x0022, DMI type 32, 20 bytes
System Boot Information
	Status: No errors detected

Handle 0x0023, DMI type 41, 11 bytes
Onboard Device
	Reference Designation:  Onboard IGD
	Type: Video
	Status: Enabled
	Type Instance: 1
	Bus Address: 0000:00:02.0

Handle 0x0024, DMI type 41, 11 bytes
Onboard Device
	Reference Designation:  Onboard LAN
	Type: Ethernet
	Status: Enabled
	Type Instance: 1
	Bus Address: 0000:00:19.0

Handle 0x0025, DMI type 41, 11 bytes
Onboard Device
	Reference Designation:  Onboard 1394
	Type: Other
	Status: Enabled
	Type Instance: 1
	Bus Address: 0000:03:1c.2

Handle 0x0026, DMI type 38, 18 bytes
IPMI Device Information
	Interface Type: KCS (Keyboard Control Style)
	Specification Version: 2.0
	I2C Slave Address: 0x10
	NV Storage Device: Not Present
	Base Address: 0x0000000000000CA2 (I/O)
	Register Spacing: Successive Byte Boundaries

Handle 0x0027, DMI type 42, 12 bytes
Management Controller Host Interface
	Interface Type: OEM
	Vendor ID: 0xFF0102FF

Handle 0x0036, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 64 GB
	Error Information Handle: Not Provided
	Number Of Devices: 4

Handle 0x0037, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x01FFFFFFFFF
	Range Size: 128 GB
	Physical Array Handle: 0x0036
	Partition Width: 4

Handle 0x0038, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0036
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_A0
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A1260F
	Asset Tag: DIMM_A0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0039, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x007FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0038
	Memory Array Mapped Address Handle: 0x0037
	Partition Row Position: 1

Handle 0x003A, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0036
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_A1
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A1277A
	Asset Tag: DIMM_A1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x003B, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x00800000000
	Ending Address: 0x00FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x003A
	Memory Array Mapped Address Handle: 0x0037
	Partition Row Position: 1

Handle 0x003C, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0036
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_B0
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A126A0
	Asset Tag: DIMM_B0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x003D, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x01000000000
	Ending Address: 0x017FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x003C
	Memory Array Mapped Address Handle: 0x0037
	Partition Row Position: 1

Handle 0x003E, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0036
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_B1
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A126A6
	Asset Tag: DIMM_B1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x003F, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x01800000000
	Ending Address: 0x01FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x003E
	Memory Array Mapped Address Handle: 0x0037
	Partition Row Position: 1

Handle 0x0040, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 64 GB
	Error Information Handle: Not Provided
	Number Of Devices: 4

Handle 0x0041, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x02000000000
	Ending Address: 0x03FFFFFFFFF
	Range Size: 128 GB
	Physical Array Handle: 0x0040
	Partition Width: 4

Handle 0x0042, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0040
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_C0
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A12674
	Asset Tag: DIMM_C0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0043, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x02000000000
	Ending Address: 0x027FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0042
	Memory Array Mapped Address Handle: 0x0041
	Partition Row Position: 1

Handle 0x0044, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0040
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_C1
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A127EB
	Asset Tag: DIMM_C1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0045, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x02800000000
	Ending Address: 0x02FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0044
	Memory Array Mapped Address Handle: 0x0041
	Partition Row Position: 1

Handle 0x0046, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0040
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_D0
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A12744
	Asset Tag: DIMM_D0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0047, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x03000000000
	Ending Address: 0x037FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0046
	Memory Array Mapped Address Handle: 0x0041
	Partition Row Position: 1

Handle 0x0048, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0040
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_D1
	Bank Locator: CPU 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A127C7
	Asset Tag: DIMM_D1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0049, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x03800000000
	Ending Address: 0x03FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0048
	Memory Array Mapped Address Handle: 0x0041
	Partition Row Position: 1

Handle 0x004A, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 64 GB
	Error Information Handle: Not Provided
	Number Of Devices: 4

Handle 0x004B, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x04000000000
	Ending Address: 0x05FFFFFFFFF
	Range Size: 128 GB
	Physical Array Handle: 0x004A
	Partition Width: 4

Handle 0x004C, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x004A
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_E0
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A127D1
	Asset Tag: DIMM_E0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x004D, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x04000000000
	Ending Address: 0x047FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x004C
	Memory Array Mapped Address Handle: 0x004B
	Partition Row Position: 1

Handle 0x004E, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x004A
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_E1
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A127D9
	Asset Tag: DIMM_E1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x004F, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x04800000000
	Ending Address: 0x04FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x004E
	Memory Array Mapped Address Handle: 0x004B
	Partition Row Position: 1

Handle 0x0050, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x004A
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_F0
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A1276E
	Asset Tag: DIMM_F0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0051, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x05000000000
	Ending Address: 0x057FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0050
	Memory Array Mapped Address Handle: 0x004B
	Partition Row Position: 1

Handle 0x0052, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x004A
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_F1
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A127E9
	Asset Tag: DIMM_F1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0053, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x05800000000
	Ending Address: 0x05FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0052
	Memory Array Mapped Address Handle: 0x004B
	Partition Row Position: 1

Handle 0x0054, DMI type 16, 23 bytes
Physical Memory Array
	Location: System Board Or Motherboard
	Use: System Memory
	Error Correction Type: Multi-bit ECC
	Maximum Capacity: 64 GB
	Error Information Handle: Not Provided
	Number Of Devices: 4

Handle 0x0055, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x06000000000
	Ending Address: 0x07FFFFFFFFF
	Range Size: 128 GB
	Physical Array Handle: 0x0054
	Partition Width: 4

Handle 0x0056, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0054
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_G0
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A126E9
	Asset Tag: DIMM_G0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0057, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x06000000000
	Ending Address: 0x067FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0056
	Memory Array Mapped Address Handle: 0x0055
	Partition Row Position: 1

Handle 0x0058, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0054
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_G1
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A12633
	Asset Tag: DIMM_G1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x0059, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x06800000000
	Ending Address: 0x06FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x0058
	Memory Array Mapped Address Handle: 0x0055
	Partition Row Position: 1

Handle 0x005A, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0054
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_H0
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A1264A
	Asset Tag: DIMM_H0_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x005B, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x07000000000
	Ending Address: 0x077FFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x005A
	Memory Array Mapped Address Handle: 0x0055
	Partition Row Position: 1

Handle 0x005C, DMI type 17, 40 bytes
Memory Device
	Array Handle: 0x0054
	Error Information Handle: Not Provided
	Total Width: 72 bits
	Data Width: 72 bits
	Size: 32 GB
	Form Factor: DIMM
	Set: None
	Locator: DIMM_H1
	Bank Locator: CPU 1
	Type: DDR4
	Type Detail: Synchronous
	Speed: 2400 MHz
	Manufacturer: Hynix Semiconductor
	Serial Number: 11A12731
	Asset Tag: DIMM_H1_AssetTag
	Part Number: HMA84GR7AFR4N-UH    
	Rank: 2
	Configured Clock Speed: 2133 MHz
	Minimum Voltage: Unknown
	Maximum Voltage: Unknown
	Configured Voltage: Unknown

Handle 0x005D, DMI type 20, 35 bytes
Memory Device Mapped Address
	Starting Address: 0x07800000000
	Ending Address: 0x07FFFFFFFFF
	Range Size: 32 GB
	Physical Device Handle: 0x005C
	Memory Array Mapped Address Handle: 0x0055
	Partition Row Position: 1

Handle 0x005E, DMI type 7, 19 bytes
Cache Information
	Socket Designation: CPU Internal L1
	Configuration: Enabled, Not Socketed, Level 1
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 1152 kB
	Maximum Size: 1152 kB
	Supported SRAM Types:
		Unknown
	Installed SRAM Type: Unknown
	Speed: Unknown
	Error Correction Type: Parity
	System Type: Other
	Associativity: 8-way Set-associative

Handle 0x005F, DMI type 7, 19 bytes
Cache Information
	Socket Designation: CPU Internal L2
	Configuration: Enabled, Not Socketed, Level 2
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 4608 kB
	Maximum Size: 4608 kB
	Supported SRAM Types:
		Unknown
	Installed SRAM Type: Unknown
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Unified
	Associativity: 8-way Set-associative

Handle 0x0060, DMI type 7, 19 bytes
Cache Information
	Socket Designation: CPU Internal L3
	Configuration: Enabled, Not Socketed, Level 3
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 46080 kB
	Maximum Size: 46080 kB
	Supported SRAM Types:
		Unknown
	Installed SRAM Type: Unknown
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Unified
	Associativity: 20-way Set-associative

Handle 0x0061, DMI type 4, 48 bytes
Processor Information
	Socket Designation: SOCKET 0
	Type: Central Processor
	Family: Xeon
	Manufacturer: Intel
	ID: F1 06 04 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 79, Stepping 1
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
	Voltage: 1.6 V
	External Clock: 100 MHz
	Max Speed: 3000 MHz
	Current Speed: 2300 MHz
	Status: Populated, Enabled
	Upgrade: Socket LGA2011-3
	L1 Cache Handle: 0x005E
	L2 Cache Handle: 0x005F
	L3 Cache Handle: 0x0060
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 18
	Core Enabled: 18
	Thread Count: 36
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control

Handle 0x0062, DMI type 7, 19 bytes
Cache Information
	Socket Designation: CPU Internal L1
	Configuration: Enabled, Not Socketed, Level 1
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 1152 kB
	Maximum Size: 1152 kB
	Supported SRAM Types:
		Unknown
	Installed SRAM Type: Unknown
	Speed: Unknown
	Error Correction Type: Parity
	System Type: Other
	Associativity: 8-way Set-associative

Handle 0x0063, DMI type 7, 19 bytes
Cache Information
	Socket Designation: CPU Internal L2
	Configuration: Enabled, Not Socketed, Level 2
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 4608 kB
	Maximum Size: 4608 kB
	Supported SRAM Types:
		Unknown
	Installed SRAM Type: Unknown
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Unified
	Associativity: 8-way Set-associative

Handle 0x0064, DMI type 7, 19 bytes
Cache Information
	Socket Designation: CPU Internal L3
	Configuration: Enabled, Not Socketed, Level 3
	Operational Mode: Write Back
	Location: Internal
	Installed Size: 46080 kB
	Maximum Size: 46080 kB
	Supported SRAM Types:
		Unknown
	Installed SRAM Type: Unknown
	Speed: Unknown
	Error Correction Type: Single-bit ECC
	System Type: Unified
	Associativity: 20-way Set-associative

Handle 0x0065, DMI type 4, 48 bytes
Processor Information
	Socket Designation: SOCKET 1
	Type: Central Processor
	Family: Xeon
	Manufacturer: Intel
	ID: F1 06 04 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 79, Stepping 1
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
	Voltage: 1.6 V
	External Clock: 100 MHz
	Max Speed: 3000 MHz
	Current Speed: 2300 MHz
	Status: Populated, Enabled
	Upgrade: Socket LGA2011-3
	L1 Cache Handle: 0x0062
	L2 Cache Handle: 0x0063
	L3 Cache Handle: 0x0064
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 18
	Core Enabled: 18
	Thread Count: 36
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection
		Enhanced Virtualization
		Power/Performance Control

Handle 0x0066, DMI type 13, 22 bytes
BIOS Language Information
	Language Description Format: Long
	Installable Languages: 1
		en|US|iso8859-1
	Currently Installed Language: en|US|iso8859-1

Handle 0x0076, DMI type 127, 4 bytes
End Of Table

EOF
